# Set the application name
spring.application.name=whatsapp-chatbot-simulation

# Server port (Default is 8080, but you can define it here)
# server.port=8080
server.port=${PORT:8080}

# Logging configuration
# This ensures your logs show up clearly in the console for your demo video
logging.level.org.springframework.web=INFO
logging.level.com.example.chatbot=DEBUG

# Database Connection Settings
# spring.datasource.url=jdbc:mysql://localhost:3306/chatbot_db?createDatabaseIfNotExist=true
# spring.datasource.username=root
# spring.datasource.password=12345

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect